# Uncomment this line to define a global platform for your project
# platform :ios, '7.0'

target 'JSONHipChat' do

pod 'hpple', '0.2.0'

end

target 'JSONHipChatTests' do

pod 'hpple', '0.2.0'

end

